name: Release tag binary and deb
on:
  push:
    tags:
      - '*'

jobs:
  run:
    name: Upload
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]
    runs-on: ${{ fromJson('{"amd64":"ubuntu-latest"}')[matrix.arch] }}
    # glibc version 2.17
    container: ${{ fromJson('{"amd64":"docker.io/ubuntu:bionic"}')[matrix.arch] }}
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.2
        id: go

      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build binary and related tools
        run: |
          apt-get update && apt-get install ruby-dev build-essential curl -y
          make build
      
      - name: Build deb package
        run: |
          export BUILD_RESULTS_DIR=debs
          export BUILD_DIR=buildroot
          export PACKAGE_NAME=chaosd-o3
          mkdir -p "${DIR}/${BUILD_RESULTS_DIR}" "${DIR}/${BUILD_DIR}/usr/bin"
          apt-get update && apt-get install ruby-dev build-essential curl grep -y && gem install fpm
          export RELEASE_VERSION=$(echo "${{ env.RELEASE_VERSION }}" | grep -Eo '[0-9.]+')
          echo $RELEASE_VERSION
          install ./bin/chaosd ${DIR}/${BUILD_DIR}/usr/bin/chaosd
          fpm -s dir -t deb --name chaosd-o3 -C "${DIR}/${BUILD_DIR}" --version $RELEASE_VERSION --iteration 1 --description "custom chaosd from Ozon Tech" -p "${PACKAGE_NAME}.deb"
          ls -la 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.RELEASE_VERSION }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.RELEASE_VERSION }}
          RELEASE: $(echo "${{ env.RELEASE_VERSION }}" | grep -Eo '[0-9.]+')
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./chaosd-o3.deb
          asset_name: chaosd-o3.deb
          asset_content_type: application/zip
